# Generated by Django 5.0.6 on 2024-05-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_image2",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
        migrations.AddField(
            model_name="product",
            name="product_image3",
            field=models.ImageField(blank=True, null=True, upload_to="product"),
        ),
    ]
